apply plugin: "com.android.application"

android {
  namespace "com.sdlui.app"

  defaultConfig {
    applicationId "com.sdlui.app"
    compileSdk 36
    minSdkVersion 29
    targetSdkVersion 36
    versionCode 1
    versionName "1.0.0"
  }

  sourceSets.main {
    jniLibs.srcDir "libs"
  }
}

dependencies {
  implementation "androidx.documentfile:documentfile:1.1.0"
  implementation "androidx.media3:media3-extractor:1.11.1"
}
